version: "3.4"

services:
  php:
    container_name: antoine.goutenoir.com_php
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      # We do not need that volume anymore, since we're using TCP not socket
      - php_socket:/var/run/php
      # We use flat files for doodles and messages, let's keep em around
      - doodles:/srv/app/var/doodle
    healthcheck:
      interval: 600s
      timeout: 3s
      retries: 2
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      # We are using a database to store messages (as in message queue), but not doodles.
      #DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}&charset=${POSTGRES_CHARSET:-utf8}
      APP_ENV: prod

  nginx:
    build:
      context: .
      target: app_nginx
    container_name: antoine.goutenoir.com_nginx
    depends_on:
      - php
    restart: unless-stopped
    #volumes:
      # use a bind-mounted host directory, as we want to keep the media
      #- ./public:/srv/app/public:ro
    # You probably want to uncomment this ; I handle network weirdly
#    ports:
#      - "80:80"
    environment:
      # Config for server's nginx-reverse-proxy container
      # move this to an un-committed override
      LETSENCRYPT_HOST: antoine.goutenoir.com
      LETSENCRYPT_EMAIL: antoine@goutenoir.com
      VIRTUAL_HOST: antoine.goutenoir.com
      VIRTUAL_PORT: 80
      ###################################################

###> recipes ###
###< recipes ###


volumes:
  php_socket:
  doodles:


# Tip from https://github.com/jwilder/nginx-proxy/issues/1132#issuecomment-392460028
# Create it first: docker network create webproxy
# You might want to remove this.
networks:
  default:
    name: webproxy
    external: true
