<?php

namespace Goutte\DoodleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DoodleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoodleRepository extends EntityRepository
{
}